# Chapter 2 数学知识和Python基础知识--一天搞定

* 传统机器学习
    * 线性回归
    * 逻辑回归
    * 决策树
    * 朴素贝叶斯
*深度学习
    * 各种复杂跨层堆叠
    

# 函数总结
* sigmoid 函数：$y(x)=\frac{1}{1+e^{-x}}$
* ReLU 函数：$y=max(x,0)$
* Leaky ReLU 函数：$y=max(\epsilon x,x)$, where $\epsilon$ is slope.

In [1]:
import math
y=math.log(100000000,10)
print("以10为底，求一亿的对数:",y)

以10为底，求一亿的对数: 8.0


## 梯度(Gradient)
**def:对多元函数求偏导数，然后把所求得的各个参数的偏导数以向量的形式写出来**

### 梯度下降：本质就是找最优化问题的一种方式，借助的工具有可能是convex analysis.




## 张量(Tensor)
**Def: 机器学习中，用于存储数据的结构叫张量！**
张量本质是一个容器：是不同维度的数组。维度称为轴，轴的个数为阶（也是张量的形状）。
eg: 标量是0D Tensor; Vector ->1D Tensor; Matrix -> 2D Tensor; 
关于Tensor 可以详见[Deep Learning with Python-Second Edition](https://www.manning.com/books/deep-learning-with-python-second-edition)

In [2]:
import numpy as np
X=np.array(5)#0D Tensor
print('X的值',X)
print('X的阶',X.ndim)
print('X的数据类型',X.dtype)
print('X的形状',X.shape)

X的值 5
X的阶 0
X的数据类型 int64
X的形状 ()


In [3]:
#1D Tensor
X=np.array([5,6,7,8,9])
print('X的值',X)
print('X的阶',X.ndim)
print('X的形状',X.shape)

X的值 [5 6 7 8 9]
X的阶 1
X的形状 (5,)


*note: 如果你也和我一样,非计算机专业，对array一知半解，可以参考任何‘数据结构’课程。* 对于我来书，[Data Structures](https://www.linkedin.com/learning/programming-foundations-data-structures-2/what-are-arrays?u=80268241)比较有帮助。

In [4]:
#Take a look at Botson_housing Datasets
from keras.datasets import boston_housing
(X_train,y_train),(X_test,y_test)=boston_housing.load_data()
print('X_train的形状：',X_train.shape)
print('X_train中第一个样本的形状',X_train[0].shape)
print('y_train的形状',y_train.shape)

X_train的形状： (404, 13)
X_train中第一个样本的形状 (13,)
y_train的形状 (404,)


In [5]:
#向量的点积
weight=np.array([1,-1.8,1,1,2])
X=np.array([1,6,7,8,9])
y_hat=np.dot(X,weight)
print('函数返回结果：',y_hat)#Dot product returns a value instead of a vector.

函数返回结果： 23.2


矩阵是2D Tensor, 形状为(样本，特征)，第一个轴为样本轴，第二个为特征轴。

In [6]:
print('X_train的内容：',X_train)

X_train的内容： [[1.23247e+00 0.00000e+00 8.14000e+00 ... 2.10000e+01 3.96900e+02
  1.87200e+01]
 [2.17700e-02 8.25000e+01 2.03000e+00 ... 1.47000e+01 3.95380e+02
  3.11000e+00]
 [4.89822e+00 0.00000e+00 1.81000e+01 ... 2.02000e+01 3.75520e+02
  3.26000e+00]
 ...
 [3.46600e-02 3.50000e+01 6.06000e+00 ... 1.69000e+01 3.62250e+02
  7.83000e+00]
 [2.14918e+00 0.00000e+00 1.95800e+01 ... 1.47000e+01 2.61950e+02
  1.57900e+01]
 [1.43900e-02 6.00000e+01 2.93000e+00 ... 1.56000e+01 3.76700e+02
  4.38000e+00]]


时间序列是一个3D Tensor

图像是4D Tensor (样本，图像高度，图像宽度，颜色深度)

视频数据是5D Tensor:(样本（视频本身），帧，高度，宽度，颜色深度)



在机器学习中，维度指的是在一个数据轴上的许多点，也就是样本的个数（样本轴上点的个数）或者特征的个数（特征轴上点的个数）

In [18]:
#2.5
list=[1,2,3,4,5]
array_01=np.array([1,2,3,4,5])
array_02=np.array((6,7,8,9,10)
print('列表：',list)
print('列表转换为数组:', array_01)
print('元组转换为数组：',array_02)#tuple to array
print('数组的形状：',array_01.shape)
print('列表的形状：',list.shape)
#Don't know why they always know errors. Need to check later.

SyntaxError: invalid syntax (<ipython-input-18-f7c6529fd0ba>, line 5)

In [21]:
array_04=np.arange(1,5,1)#首：尾：步长
array_05=np.linspace(1,5,5)#1到5之间分成5份，首：尾：份数
print(array_04)
print(array_05)

[1 2 3 4]
[1. 2. 3. 4. 5.]


In [23]:
array_06=np.arange(10)
print(array_06)
index_01=array_06[3]
print('第4个元素：',index_01)
index_02=array_06[-1]#the last
print('第-1个元素：',index_02)
slice_01=array_06[:4]
print('从0到4切片：',slice_01)
slice_02=array_06[1:12:4]
print('从0到12切片，步长为4',slice_02)


[0 1 2 3 4 5 6 7 8 9]
第4个元素： 3
第-1个元素： 9
从0到4切片： [0 1 2 3]
从0到12切片，步长为4 [1 5 9]


In [24]:
array_07=np.array([[1,2,3],[4,5,6]])
print(array_07[1:2],'它的形状是',array_07[1:2].shape)
print(array_07[1:2][0],'它的形状又不同了',array_07[1:2][0].shape)

[[4 5 6]] 它的形状是 (1, 3)
[4 5 6] 它的形状又不同了 (3,)


In [25]:
array_07+=1#都加1
print(array_07)


[[2 3 4]
 [5 6 7]]


In [26]:
#Tensor reshape
print(array_07,'形状是',array_07.shape)
print(array_07.reshape(3,2),'THE SHAPE IS',array_07.reshape(3,2).shape)

[[2 3 4]
 [5 6 7]] 形状是 (2, 3)
[[2 3]
 [4 5]
 [6 7]] THE SHAPE IS (3, 2)


In [27]:
array_07=array_07.T
print(array_07)

[[2 5]
 [3 6]
 [4 7]]


In [28]:
print(array_06,'the shape is',array_06.shape,'the rank is:',array_06.ndim)
array_06=array_06.reshape(10,1)
print(array_06,'the shape is',array_06.shape,'the rank is:',array_06.ndim)

[0 1 2 3 4 5 6 7 8 9] the shape is (10,) the rank is: 1
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] the shape is (10, 1) the rank is: 2


In [30]:
#Broadcast in python
array_08=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
array_09=np.array([[0,1,2]])
array_10=np.array([[0],[1],[2],[3]])
list_11=[[0,1,2]]
print('array_09 的形状：',array_09.shape)
print('array_10 的形状：',array_10.shape)
array_12=array_09.reshape(3)
print('array_12 的形状：',array_12.shape)
array_13=np.array([1])
print('array_13 的形状：',array_13.shape)
array_14=array_13.reshape(1,1)
print('array_14 的形状：',array_14.shape)
print('08+09 Result',array_08+array_09)
print('08+10 Result',array_08+array_10)
print('08+11 Result',array_08+list_11)
print('08+12 Result',array_08+array_12)
print('08+13 Result',array_08+array_13)
print('08+14 Result',array_08+array_14)

array_09 的形状： (1, 3)
array_10 的形状： (4, 1)
array_12 的形状： (3,)
array_13 的形状： (1,)
array_14 的形状： (1, 1)
08+09 Result [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
08+10 Result [[ 0  0  0]
 [11 11 11]
 [22 22 22]
 [33 33 33]]
08+11 Result [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
08+12 Result [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
08+13 Result [[ 1  1  1]
 [11 11 11]
 [21 21 21]
 [31 31 31]]
08+14 Result [[ 1  1  1]
 [11 11 11]
 [21 21 21]
 [31 31 31]]


In [34]:
vector_01=np.array([1,2,3])
vector_02=np.array([[1],[2],[3]])
vector_03=np.array([2])
vector_04=vector_02.reshape(1,3)
print('vector_01 shape:',vector_01.shape)
print('vector_02 shape:',vector_02.shape)
print('vector_03 shape:',vector_03.shape)
print('vector_04 shape:',vector_04.shape)
#我对书里对以上解释有疑问
print('the dot product of 01 and 01',np.dot(vector_01,vector_01))
print('the dot product of 01 and 02',np.dot(vector_01,vector_02))
print('the dot product of 04 and 02',np.dot(vector_04,vector_02))
print('the dot product of 01 and number',np.dot(vector_01,2))
print('the dot product of 02 and 03',np.dot(vector_02,vector_03))
print('the dot product of 02 and 04',np.dot(vector_02,vector_04))
print('the dot product of 01 and 03',np.dot(vector_01,vector_03))
print('the dot product of 02 and 02',np.dot(vector_02,vector_02))

vector_01 shape: (3,)
vector_02 shape: (3, 1)
vector_03 shape: (1,)
vector_04 shape: (1, 3)
the dot product of 01 and 01 14
the dot product of 01 and 02 [14]
the dot product of 04 and 02 [[14]]
the dot product of 01 and number [2 4 6]
the dot product of 02 and 03 [2 4 6]
the dot product of 02 and 04 [[1 2 3]
 [2 4 6]
 [3 6 9]]


ValueError: shapes (3,) and (1,) not aligned: 3 (dim 0) != 1 (dim 0)